[package]
name = "rust-llm"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = [
    "wgpu",
    "ndarray",
    "tui",
    "metrics",
    "train",
] }
tiktoken-rs = "0.7.0"
